### ISSUE TITLE
bildegalleri singlevisning fungerer ikke

### ISSUE THREAD

**Issue by zrrrzzt** [telemark/telemarkBundle#100]
http://www.telemark.no/Vaare-tjenester/Tannhelse/Tannklinikker/Seljord-tannklinikk/Bildegalleri2/bildegalleri/Seljord-Tannklinikk

**Comment by Paalmessenlien** [comment]
Her må det nok kodes inn en del ekstra. Så kanskje vi skal vurdere om den skal skrives om til symf kode istedenfor å bruke opp igjen legacy koden? Tar en hangout til uka om dette.

**Comment by zrrrzzt** [comment]
Jeg kan finne frem koden til den forrige

**Comment by zrrrzzt** [comment]
Denne kan løses ved å embedde galleriet i en artikkel i stedet for å peke direkte til det.
