### ISSUE TITLE
mangler grid-wrapper rundt grid-items på landingssider

### ISSUE THREAD

**Issue by zrrrzzt** [telemark/telemarkBundle#101]
http://www.telemark.no/Vaare-tjenester

**Comment by evasdrugg** [comment]
Er dette samme greia? 

http://www.telemark.no/Vaare-tjenester/Utdanning/Aktuelt

**Comment by KnutSv** [comment]
Ja det er samme bug

**Comment by zrrrzzt** [comment]
nei, aktuelt oppfører seg som den skal. den har grid-wrapper. den fremstår slik fordi det første elementet er en linkblokk og resten er artikler. ulikt innhold listes ikke opp i samme grid

**Comment by evasdrugg** [comment]
Men her er det hvitt? http://www.telemark.no/Vaare-tjenester/Utdanning/Aktuelt

**Comment by zrrrzzt** [comment]
som jeg sa: "fremstår slik fordi det første elementet er en linkblokk og resten er artikler. Ulikt innhold listes ikke opp i samme grid"

Denne siden har to ulike former for innhold og de listes i hver sin "boks".
