### ISSUE TITLE
Mediabibliotek, filer oppdateres ikke

### ISSUE THREAD

**Issue by zrrrzzt** [telemark/telemarkBundle#102]
Laster opp ny pdf i eksisterende fil (for å spare tid/oppdatere) - eZ registrerer ikke

**Comment by Paalmessenlien** [comment]
Trenger ett eksempel. Klarer ikke å gjenskape problemet.

**Comment by evasdrugg** [comment]
Dette ser ut til å fungere nå.

**Comment by zrrrzzt** [comment]
Da erklærer vi denne for "løst"
