### ISSUE TITLE
For mye vises i søk

### ISSUE THREAD

**Issue by zrrrzzt** [telemark/telemarkBundle#103]
Ønsker at kun artikler, mapper og personprofil skal tas med i søk

Søk f.eks. på "Logo"

Også feil når man trykker på et av treffene: http://www.telemark.no/Fylkeskommunen/Grafisk-profil-og-logo/Logo gir 404

**Comment by zrrrzzt** [comment]
Ser ut til at utvalget er bedre nå. Men det er fortsatt 404 på denne http://www.telemark.no/Fylkeskommunen/Grafisk-profil-og-logo/Logo

**Comment by Paalmessenlien** [comment]
Meldt tilbake

**Comment by Paalmessenlien** [comment]
Fra MM: JA, den "Logo" var skjult i admin. Jeg har nå lagt inn sjekk på visibility på søket (rart det ikke var default)
