### ISSUE TITLE
Kampanjefelt: Ny versjon

### ISSUE THREAD

**Issue by zrrrzzt** [telemark/telemarkBundle#107]
Ønsker tre kampanjer i bredden (på forsiden) som rulles tre og tre.

Ved små skjermer går man over til å vise 1 og en

**Comment by KnutSv** [comment]
Dette er ikke noe som støttes i javascript-slideren vi bruker. Det er i utg.punktet ikke vanskelig å vise tre bilder per slide, men utfordringen er å ha forskjellig visning på forskjellige skjermoppløsninger.

Er det en grei løsning at antall kolonner som vises avgjøres når siden lastes, slik at man ikke endrer antall kolonner ved å skalere siden opp eller reduserer antall kolonner ved å skalere siden ned?

**Comment by zrrrzzt** [comment]
Ja, det er en grei løsning. Man mister da evt fleksibilitet om man endrer størrelse på nettleseren undervegs. Men, den er jeg villig til å la fare.

**Comment by evasdrugg** [comment]
Skjer det noe her? For meg og fagredaktørene er det viktig å få til et bedre utseende for kampanjefelt.

**Comment by zrrrzzt** [comment]
@evasdrugg Dette er definert som tillegg og dermed vil det være utviklingskostnader tilknyttet. Jeg vil først gjerne ha time overslag fra @KnutSv før vi bestiller

**Comment by evasdrugg** [comment]
Ok, da venter vi i spenning @zrrrzzt @KnutSv

**Comment by KnutSv** [comment]
Litt rask estimering tilsier at dette er en dagsjobb: 7,5 timer

**Comment by zrrrzzt** [comment]
Kjør på :+1:

**Comment by evasdrugg** [comment]
Dette står høyest på ønskelista mi - hvordan går det her? @KnutSv @zrrrzzt

**Comment by zrrrzzt** [comment]
@KnutSv sitter på alle svarene :-)

**Comment by KnutSv** [comment]
Pga. sykdom har jeg ikke fått begynne på dette denne uka slik jeg håpet. Skal prøve å ta det i løpet av neste uke.

**Comment by evasdrugg** [comment]
Gyldig grunn :) Gleder meg til å se forslag.

**Comment by KnutSv** [comment]
Ny tre-delt slider klar på prod

**Comment by KnutSv** [comment]
I rammeverket har jeg endret kode for bildene slik at vi laster bilder responsivt i riktig størrelse, på telemarkBundle er dette en liten utfordring ettersom bildekoden er brukt flere steder (for toppbilder generelt).

**Comment by KnutSv** [comment]
Nevermind, ser at det er egen kode for slider, fikser det og legger ut. Sorry for spam.

**Comment by evasdrugg** [comment]
Kan vi åpne denne igjen @KnutSv @zrrrzzt ?

 Vi var ikke helt fornøyd - og det er bestillingens skyld - men nå har vi fått pratet litt og blitt enige om ønsket kampanjefelt. 

Sjekk http://www.akershus.no/ og http://www.rogfk.no/. Kun rette streker for oss, ikke bølgete bokser. Fint med hvitt mellomrom. Prikker for å markere at det er flere bilder og piler til venstre og høyre ala Akershus.

Bakgrunnsfarge for tekstfelt: https://designguide.t-fk.no/farger-og-typografi/fargepalett-web/ Jeg foreslår -#007c97. Hvit tekst over. Viktig at "Prosjekter" og "Ledige stillinger"- lenker er varianter av denne fargen - men da kan kansje du ta @zrrrzzt?

**Comment by zrrrzzt** [comment]
Foreslår at det heller åpnes en ny issue @evasdrugg

**Comment by evasdrugg** [comment]
OK
