### ISSUE TITLE
Kunne høyrestillebilder i responsiv utgave

### ISSUE THREAD

**Issue by zrrrzzt** [telemark/telemarkBundle#109]
Ønsker å kunne høyrestiller bilder i tekst slik at teksten legger seg rundt.

På små skjermer skal bildet sentreres med tekst kun over og under

**Comment by zrrrzzt** [comment]
Estimat på denne plz?

**Comment by KnutSv** [comment]
2 timer

**Comment by zrrrzzt** [comment]
Deal :+1:
