### ISSUE TITLE
Ønsker to linkblokker i stedet for tre i bredden på vanlige mappe/artikkelsider

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#110]
http://www.telemark.no/Fylkeskommunen/OEkonomi 

Det var to bokser i bredden (+ evt infoboks) før, ikke tre som nå. Ønsker to bokser i bredden der det er infobokser, og dersom det ikke er infobokser, tre bokser som benytter hele bredden.

**Comment by evasdrugg** [comment]
:)

**Comment by evasdrugg** [comment]
Skjer det noe her?

**Comment by Maiskolba** [comment]
Sånn: http://devtelemark.vangenplotz.net/Fylkeskommunen/OEkonomi ?

**Comment by zrrrzzt** [comment]
Ja, akkurat slik :-)

Rull ut

**Comment by evasdrugg** [comment]
Hurra
