### ISSUE TITLE
Ord brytes i linkblokk

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#112]
http://www.telemark.no/Vaare-tjenester/Utdanning/For-privatister  

Se "Under eksamen", "Vurderingsveiledn"

Det ser riktig ut i eZ. http://www.telemark.no/siteadmin/content/edit/1152/30/nor-NO

**Comment by KnutSv** [comment]
Hvilken nettleser brukes når problemet oppstår? Har testet i Chrome på Mac og Internet Explorer 9 på Windows og kan ikke gjenskape problemet.

Hos meg fortsetter resten av ordet på neste linje. Ikke veldig elegant, men ikke mye mer man kan gjøre når det er liten plass og lange ord på web.

**Comment by evasdrugg** [comment]
Bruker Chrome.. På PC. Men det skal ha sett ok ut tidligere. Men quick fix er jo å prøve å fjerne infoboks evt korte ned ord.

**Comment by KnutSv** [comment]
![chrome41win](https://cloud.githubusercontent.com/assets/821570/7412037/d5e423ea-ef3e-11e4-8b9a-3e7e3e83a4f1.png)

Ser greit ut hos meg med Chrome 41 på Windows 7

**Comment by zrrrzzt** [comment]
Vil vel ikke si det ser greit ut med eksamensregleme\nnt men

**Comment by KnutSv** [comment]
Greit i den forstand at ordene ikke forsvinner. Men enig i at det ikke er optimalt.

Tekstbryting er noe av det som ikke er støttet godt i nettlesere enda, hvertfall ikke for norsk språk.

**Comment by zrrrzzt** [comment]
Har en vag fornemmelse av at vi slo av "fancy" tekstbryting på releasedagen. Mulig det er bivirkninger av dette som plager enkelte nettlesere.

**Comment by evasdrugg** [comment]
@KnutSv Jeg mente ikke at ord forsvant... Sorry, det er fredag på en torsdag. Men det ser likt ut hos meg. Men synes ikke det ser greit ut med orddelingen.

**Comment by zrrrzzt** [comment]
Ord brytes nå "rart" flere steder. http://www.telemark.no/Vaare-tjenester/Folkehelse/Aktuelt/Ung-i-Telemark-konferanse-21.-og-22.-oktober-2015 denne siden i FireFox på Mac har også masse pussigheter.

Jeg foreslår at vi setter word-wrap: normal i css. Dette ble gjort på serveren releasedagen og alle ble fornøyde. Ting tyder på at dette ikke ble lagt inn også i malverket slik at "feilen" har kommet tilbake ved senere oppdateringer.
