### ISSUE TITLE
Ønsker hvit bakgrunn og sort tekst på bildetekster

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#113]
Bildetekst og fotobyline tar for mye oppmerksomhet. Nøytral bakgrunn? 

http://www.telemark.no/Aktuelt/Endring-i-skoleskyssordningen

Geir, fint om man bare får plass til å skrive inn bildetekst ETT sted, og ikke to muligheter.

**Comment by zrrrzzt** [comment]
@evasdrugg utdyp dette med mulighet for bildetekster flere steder

**Comment by evasdrugg** [comment]
Bildetekst og fotobyline ingressbilde. Og bildetekst i bildet som plasseres i artikkel.

**Comment by evasdrugg** [comment]
Når får du/dere gjort noe her @zrrrzzt?
