### ISSUE TITLE
Automatisk redirect når man skal laste ned filer

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#115]
Når man trykker på en lenke til PDF, så åpner det seg et nytt vindu, før det lastes ned. 

 http://www.telemark.no/Media/Files/Aktuelt/Lokalmat-forprosjekt

Har man lagt inn beskrivelse av fil, kommer dette også med. Unødvendig.

http://www.telemark.no/Media/Files/Utdanning/Skjemaer-og-vedlegg/Individuell-behandling

**Comment by zrrrzzt** [comment]
Beskrivelse av filer hører hjemme på filobjektet. Men jeg er enig i at det er ønskelig at filer man linker til direkte skal lastes ned

**Comment by evasdrugg** [comment]
Ja, mente det var unødvendig at beskrivelsen kom med på side nummer to. Dette problemer forsvinner jo ved direkte nedlasting.

**Comment by evasdrugg** [comment]
Skjer det noe her?

**Comment by evasdrugg** [comment]
Skjer det noe her?

**Comment by Maiskolba** [comment]
Dette kommer an på hvordan dere legger inn filen. Ta en kikk her: http://devtelemark.vangenplotz.net/Vaare-tjenester/Naeringsutvikling/Artikler/Framtidsverksted-for-lokalmat-og-reiseliv - under Program.
Den øverste er lagt inn som en link til en fil i mediabiblioteket. Da kommer man til en egen side.
Den andre er lagt inn som et objekt (bindersen) fra mediabiblioteket, da kan man laste den direkte ned.

**Comment by zrrrzzt** [comment]
Den gamle løsningen vår hadde en redirect på filer når de ble linket til mediabiblioteket. Det er slik vi ønsker at det skal være nå også.

**Comment by Maiskolba** [comment]
Kan hende det er feriemodusen som har startet, men jeg forstår ikke helt hva dere mener.. Hva mener dere med redirekt og hva er forskjellen på det og den nederste linken i eksempelet ovenfor?

**Comment by Paalmessenlien** [comment]
I den gamle løsningen så hadde jeg lagt inn en endring som gjorde at hvis
man linket til en fil med vanlig lenke funksjon så ble det en link direkte
til filen og ikke til selve objektet. Om vi får til det samme i symfony vet
jeg ikke. Dette er noe som eZ egentlig burde ha tenkt på.
1. juli 2015 kl. 10.56 skrev Maiskolba notifications@github.com:

**Comment by zrrrzzt** [comment]
det @Paalmessenlien sa :-)

**Comment by Maiskolba** [comment]
Det vil si at vanlig lenke funksjon ble konvertert til objekt funksjonen? For da skal de i praksis gjøre det samme?

**Comment by Paalmessenlien** [comment]
Med objekt så kan man vel ikke velge selv hva som skal stå i lenken?..
Eks.. Last ned fil her..

2015-07-24 11:10 GMT+02:00 Maiskolba notifications@github.com:

**Comment by Maiskolba** [comment]
Aha, da forstår jeg!

**Comment by evasdrugg** [comment]
Blir det no automatisk redirect snart? Ser at det fremdeles går via en ekstra side når man skal laste ned http://www.telemark.no/Media/Files/Folkehelse/Materiell-fra-Folkehelse/Tilbudshefte-2015-2016

**Comment by zrrrzzt** [comment]
Denne funksjonen er inne i nyere versjon av eZ http://share.ez.no/blogs/community-project-board/ez-platform-15.05-is-available Mao bedre å vente til neste oppgradering (som sikkert blir når man kommer i gang med server for skolesidene) enn å hacke sammen noe midlertidig legacy-stuff

**Comment by evasdrugg** [comment]
OK - da er denne på vent inntil videre?

**Comment by zrrrzzt** [comment]
Den blir utført i form av oppgradering og ikke egenutvikling. Kan dessverre ikke gi tidspkt for oppgradering ennå.

**Comment by evasdrugg** [comment]
Okei.
