### ISSUE TITLE
Facebookboks er borte fra sidene

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#116]
Hei, ser ut som om Facebookbokse til Telemark fylkeskommunes facebookkonto er borte fra denne siden: http://www.telemark.no/Fylkeskommunen

og Facebookboks til Team internasjonalt sin facebookkonto er borte fra http://www.telemark.no/Vaare-tjenester/Internasjonalt-arbeid

**Comment by zrrrzzt** [comment]
Vi må ha en embed-klasse for symfony. Gir du estimat @Paalmessenlien ?

**Comment by evasdrugg** [comment]
Åssen er ståa her?

**Comment by Maiskolba** [comment]
Er dette ren html som skal legges i infobokser?

**Comment by zrrrzzt** [comment]
Ja. Det mener jeg er hva som skal gjøres.

**Comment by Maiskolba** [comment]
f.eks sånn: http://devtelemark.vangenplotz.net/Fylkeskommunen?

**Comment by zrrrzzt** [comment]
Har bare nettbrett og der så det litt pussig ut, men det er kanskje mer
FB-kodens skyld.
Om du mener det ser OK ellers stoler jeg på det.

**Comment by Maiskolba** [comment]
Ja, jeg var litt usikker på hvilken fb-kode dere har brukt tidligere. Men jeg har ihvertfall lagt inn facebook sdk, slik at dere kan benytte dere av ulike fb-koder. Det lå allerede inne en mulighet for å legge ti literal-tagger, og der velge html.

**Comment by zrrrzzt** [comment]
Sender du meg dokumentasjonen på de ulike fb-kodene på e-post?

**Comment by Maiskolba** [comment]
Det er lettere hvis du går inn her: https://developers.facebook.com/docs/plugins/page-plugin
Da er det bare å plotte inn f.eks https://www.facebook.com/telemarkfylke?fref=ts i Facebook Page URL og endre innstillingene selv. Var det forresten en sånn type boks dere hadde på den gamle løsningen?
