### ISSUE TITLE
Vis sist oppdatert dato i artikler på listevisning

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#117]
Har snakket med fagredaktører om at vi ønsker "Oppdatert"-dato på artikler. Dette gjelder kun på listevisning. Vi er fornøyd med at det står "Publisert og oppdatert" dato i selve artikkelen.

http://www.telemark.no/Vaare-tjenester/Folkehelse/Barnehager/Kosthold

Det ser gammelt ut når en artikkel ble publisert i 2012, men oppdatert i 2014 - og det er 2012-dato som vises.

Nyhetsartikler skal ha "Publisert-dato" på listevisning.

**Comment by evasdrugg** [comment]
@zrrrzzt Veit jeg er kravstor. Men går det an at artikler i flikboks på forside www.telemark.no har "Publisert"-dato? Gjerne også på "min" Aktueltside, http://www.telemark.no/Aktuelt

**Comment by zrrrzzt** [comment]
Du kan gjerne åpne en issue på det @evasdrugg , men magefølelsen min sier wontfix ;-)

**Comment by evasdrugg** [comment]
Okei!
