### ISSUE TITLE
Får ikke postet artikkel med bilde på Facebook

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#118]
Prøver å poste artikkel på Facebook, men bildet kommer ikke opp. Dette har det vært problemer med tidligere.

http://www.telemark.no/Vaare-tjenester/Utdanning/Aktuelt/Denne-hytta-kan-bli-din

**Comment by zrrrzzt** [comment]
For å sjekke hvordan Facebook ser artikkelen kan du bruke deres Open Graph Debug tool: https://developers.facebook.com/tools/debug

Sjekket artikkelen du viser til her og den ser helt tipp topp ut. Så ingen bug funnet. Sikkert solflekker ;-)

**Comment by evasdrugg** [comment]
@zrrrzzt Det funker ikke i praksis da, det er vel det viktigste. Jeg var akkurat på developorssida til FB, og der ser det jo bra ut. Men nå har jeg prøvd med ulike artikler to-tre dager, og det funker ikke. Gå inn og prøv selv på Facebook?  

http://www.telemark.no/Vaare-tjenester/Miljoe-og-friluftsliv/Aktuelt/Turer-med-guide-i-geoparken

**Comment by zrrrzzt** [comment]
Vi kan ikke gjøre noe med dette @evasdrugg Når verktøyene til Facebook sier vi gjør alt korrekt har vi ingen feil å fikse. Problemet tidligere var at meta tags for Open Graph ikke var lagt inn. Etter at det ble gjort og løsningen validerte på developer-sidene til FB har ting fungert. Vet ikke hvorfor det ikke gjør det nå, og har ingen mulighet til å fikse det før developer-siden til FB gir oss feilmelding.

Beklager

**Comment by zrrrzzt** [comment]
![screen shot 2015-05-08 at 09 40 19](https://cloud.githubusercontent.com/assets/2197936/7532383/7a8fb0e4-f566-11e4-814a-60e4943b8938.png)

Fra min maskin nettopp nå

**Comment by evasdrugg** [comment]
Da har bare Facebook ikke likt meg for tiden... men nå fikk jeg det til! Veldig rart.

**Comment by zrrrzzt** [comment]
Bugs er vanlig i software det... bare at denne gang var det ikke hos oss.
