### ISSUE TITLE
Strukturering av arkivnyheter under Aktuelt

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#121]
Hei, husker vi snakket om mappene for årstall - og at du kanskje skulle gjøre noe for å strukturere mappene - husker du? Har bare to mapper, en for 2012 og en for 2013.

http://www.telemark.no/Aktuelt

**Comment by zrrrzzt** [comment]
Tror mitt opprinnelige forslag var at dere oppretter mapper for hvert år og legger artiklene direkte inn i mappen den hører hjemme. Da slipper man å flytte den senere.
Når det gjelder hvordan det vil slå ut med spesialvisningen må nesten @Paalmessenlien svare på.
Tror det i verste fall handler om å endre litt på søket som gjøres.

**Comment by evasdrugg** [comment]
Åh, trodde du hadde en magisk løsning, derfor jeg venta. Ingen artikler ligger i 2014 - mappe, det blir gøy!

**Comment by zrrrzzt** [comment]
Min løsning var "Først legg i mapper"... så, kanskje ... magi ;-)

**Comment by evasdrugg** [comment]
Jeg har lagt i mapper for alle år, utenom 2015 - tenkte jeg måtte snakke med deg før dette, pga visning. Men ser nå at når jeg trykker i 2014-mappen, så vises ikke alle artikelene. Litt krise.

http://www.telemark.no/Aktuelt/2014
