### ISSUE TITLE
Meny vise alle elementer

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#124]
Dette er fra Lene:

Kan du få denne menyen til å vise «alle elementer» -  http://www.telemark.no/Vaare-tjenester/Folkehelse/Tilbud-HEFRES - det er en haug artikler som ligger under her, men den viser bare 20…

På aktuelt-menyen vår vises også bare de siste 20 artiklene. Kan vi få de eldre artiklene til å legge seg automatisk inn i en undermeny som f.eks. kalles «arkiv»? Eller må det evt gjøres manuelt dersom en fortsatt ønsker å ha artiklene liggende ute?

Eva Susanne: dette har jeg meldt inn tidligere, har jeg ikke?

**Comment by zrrrzzt** [comment]
Det kan se ut til at limit er satt til 20 for underobjekter @Paalmessenlien 
Mener årsaken til det var at enkelte mapper hadde så mye at hele siten ble kvalt. Skru den opp til 40 i første omgang, så ser vi om ikke noe kan/bør fikses med omstrukturering også.
