### ISSUE TITLE
Meny på iPad/nettbrett vises ikke

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#125]
Fra Lene:Når jeg går inn på www.telemark.no på ipaden og trykker på menyen (den gule firkanten med linjene) kommer ikke menyen opp – det hopper bare ned til bunnen av siden. I tillegg ligger søkefeltet over de to gule knappene for søk og meny – det ser litt rart ut ;)

**Comment by Paalmessenlien** [comment]
Testet på en ipad 2 her med safari og det fungerer der. Dette kan ha vært et problem fra før vi slettet cache og kjørte rebuild. Kan du be dem teste igjen?

**Comment by evasdrugg** [comment]
Virker fremdeles ikke @Paalmessenlien

**Comment by evasdrugg** [comment]
Sjekket på min iPad nå, samme greia @Paalmessenlien - har akkurat opppdatert til ny ios.

**Comment by KnutSv** [comment]
Var et problem med media queries på iPad i landskap-modus.
