### ISSUE TITLE
img/srcset/picture kombinasjonen validerer ikke

### ISSUE THREAD

**Issue by zrrrzzt** [telemark/telemarkBundle#128]
Gjelder bildene brukt i kampanjekarusellen bl.a. på forsiden

http://validator.w3.org/check?uri=http%3A%2F%2Fwww.telemark.no%2F&charset=%28detect+automatically%29&doctype=Inline&group=0&user-agent=W3C_Validator%2F1.3+http%3A%2F%2Fvalidator.w3.org%2Fservices

**Comment by Paalmessenlien** [comment]
Fikset

**Comment by vangpl** [comment]
Fikset igjen.
