### ISSUE TITLE
Kun en bildetekst

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#129]
Hei, vi ønsker at det kun skal være en bildetekst i eZ - alltid vært forvirrende med to. Tittel på feltet kan være "Bildetekst".

**Comment by zrrrzzt** [comment]
Kan du utdype litt? Gjerne med linker til eksempler.

**Comment by evasdrugg** [comment]
Ingressbilde tittel og Ingressbilde tekst heter feltene. Se eksempel når jeg har fylt ut begge her:

http://www.telemark.no/Vaare-tjenester/Kultur-og-idrett/Aktuelt/Fylkesbiblioteket-ut-paa-hoering

**Comment by zrrrzzt** [comment]
Bildetittel og tekst er to ulike felter. Ser at i den nye utgaven er de formattert likt og ikke slik de var på de forrige websidene. Kan legge inn issue på å endre formattering om ønskelig.

**Comment by evasdrugg** [comment]
Men jeg vil jo fremdeles at det kun skal være én bildetekst - slik det som regel er i aviser/på nett. Eksempel: http://www.ta.no/har-de-norges-beste-kantine/s/5-50-86468 "Kokketeamet" regnes som del av bildeteksten. 

Ønsker altså IKKE bildetittel, kun bildetekst - kan jeg ikke få vilja mi her? Vær så snill? @zrrrzzt

**Comment by zrrrzzt** [comment]
Dette er ikke noen fanesak for meg, men hva blir konsekvensen av sletting?
Hvor mange bilder blir "meningsløse" om jeg sletter et av feltene? Det er pr nå 1340 artikler på siden. Skal jeg fjerne tittel... eller tekst?

**Comment by evasdrugg** [comment]
Det var jo et veldig godt spørsmål. La meg tenke på.

**Comment by zrrrzzt** [comment]
kommet til noen konklusjon @evasdrugg ?

**Comment by evasdrugg** [comment]
Jeg foreslår at vi beholder den øverste, Ingressbilde tittel - og bytter navn på feltet til "Bildetekst"?

**Comment by zrrrzzt** [comment]
ok, lager ny issue på det

**Comment by evasdrugg** [comment]
Hvilken issue er ny? For det er fremdeles to bildetekster?
