### ISSUE TITLE
Endre mappevisning under Aktuelt

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#131]
Har lagt artikler i mapper t.o.m. 2014. Men viser ikke lenger enn til 20. mai. Har jeg meldt inn dette tidligere?

http://www.telemark.no/Aktuelt/2014

Veldig viktig!

**Comment by zrrrzzt** [comment]
Måten Aktuelt er bygget opp gjør at det er fryktelig mange artikler under hver årstallsmappe. Pga hastighet har vi satt maks underinnhold til 20 pr nivå. Dette er nå justert opp til 40, men er fortsatt ikke nok.

Mitt forslag: Lage samme bla/filtervisning på undermappene i Aktuelt som på forsiden, men med f.eks. 12 pr side i stedet for 6 som er tilfelle på forsiden.

 @Paalmessenlien dette kan dere bare gjøre, med mindre man snakker dagesvis med utvikling, da vil vi gjerne ha et overslag først.

**Comment by zrrrzzt** [comment]
Status: @KnutSv kommer med et forslag til den ultimate visning av aktuelt/nyhetsarkiv ... ever. Uavhengig  av hvordan mappestrukturen er.

**Comment by KnutSv** [comment]
Det virker på meg som den beste løsningen er paginering slik det allerede er under aktuelt:
http://www.telemark.no/Aktuelt

Jeg assigner denne til Pål da jeg ikke har jobbet noe med backend på denne løsningen

**Comment by Paalmessenlien** [comment]
Kunne vi laget en avkryssning på folder klassen, eller hvis den er krysset av for vis undersider så legg inn paginator visning slik som på aktuelt. Vil dette påvirke andre steder hvor det ikke er behov for paginator?

**Comment by zrrrzzt** [comment]
Jeg er veldig for konfigurasjon vha avkrysning. Det er et par områder til jeg vet kunne hatt godt av paginator.

**Comment by zrrrzzt** [comment]
Vedr avkrysning og mappekonfigurasjon:

Drømmeløsningen ville være om man f.eks. kunne sette opp at man vil vise f.eks de 20 siste artiklene fra området uansett undermapper og så kunne si at man vil vise de i bolker på 5 og 5.

**Comment by Maiskolba** [comment]
Er det greit at jeg legger til avkrysning på mapper om man vil vise paginator, og et felt hvor man fyller inn antall som skal vises per side? Er litt usikker på hva som menes med å vise de siste 20 artiklene fra området uansett undermapper.. på f.eks Aktuelt/2014, så hentes bare de artiklene som ligger i den mappa? Samme gjelder /Aktuelt, det hentes bare ut de som legger rett under Aktuelt?

**Comment by zrrrzzt** [comment]
Avkrysning og felt for antall er ok.

Hente de siste 20 uansett undermapper vi i tilfellet /Aktuelt si at de siste 20 vises enten de ligger på rot eller i undermapper. Skulle noen legge en ny artikkel i 2014-mappen skal mao den også vises på forsiden (om den er av de siste nye). Så det blir mer en smart-mappe enn trad. mappevisning

**Comment by Maiskolba** [comment]
Da har jeg lagt inn mulighet for paginering, se eksempel her:

Jeg er litt usikker på hvordan vi kan løse det med å vise 20 siste uansett om det er i rot eller i undermapper på førstesiden. Vi sender med en spørring til pagineringen, så vi må enten definere at den skal hente elementer i rot eller i begge deler. Kan vi avvente med denne? Kanskje Pål har noen innspill. 

Når det gjelder /Aktuelt kan vi kanskje der hente alle artikler fra både rot og i undermapper, men begrense det til de som ikke er eldre enn 1 år f.eks? Da vil dere få synliggjort de artiklene som legges i en undermappe, men som er ny..

**Comment by zrrrzzt** [comment]
Stemmer, aktuelt har egen visning. Ja jeg er er enig, du trenger ikke engang ta siste år. Ta siste 6 mnd.
Meningen er at vi skal begynne å legge inn alle artikler i mappen for årstallet de publiseres. Da vil siste 6 mnd uansett være bra.

Lukker denne nå, så kan vi evt åpne en ny for "Smartmapper"
