### ISSUE TITLE
Søkefelt legger seg over meny på iPad

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#132]
Søkefeltet legger seg over den gule firkantboksmenyen. Ser rart ut.

**Comment by zrrrzzt** [comment]
Får du til å ta en skjermdump av denne @evasdrugg ?

**Comment by evasdrugg** [comment]
Trenger jeg å ta skjermdump nå som du har sett det sjæl, @zrrrzzt?

**Comment by zrrrzzt** [comment]
Er ikke jeg som trenger skjermdumpen @evasdrugg

**Comment by evasdrugg** [comment]
![img_0544](https://cloud.githubusercontent.com/assets/12184881/8201431/3f7de608-14d1-11e5-9709-63a9814cd98f.PNG)

Soleis.

**Comment by KnutSv** [comment]
Samme som #125
