### ISSUE TITLE
Nytt kampanjefelt

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#135]
Vi var ikke helt fornøyd - og det er bestillingens skyld - men nå har vi fått pratet litt og blitt enige om ønsket kampanjefelt.

Sjekk http://www.akershus.no/ og http://www.rogfk.no/. Kun rette streker for oss, ikke bølgete bokser. Fint med hvitt mellomrom. Prikker for å markere at det er flere bilder og piler til venstre og høyre ala Akershus.

Bakgrunnsfarge for tekstfelt: https://designguide.t-fk.no/farger-og-typografi/fargepalett-web/ Jeg foreslår -#007c97. Hvit tekst over. Viktig at "Prosjekter" og "Ledige stillinger"- lenker er varianter av denne fargen - men da kan kansje du ta @zrrrzzt?

**Comment by KnutSv** [comment]
Skjønner ikke hva du mener her. Du vil ha knæsj grønn bakgrunn med striper? Dette kommer i så fall til å bli veldig tungt og dominerende på siden og bryte med designprofilen. 

Jeg valgte å bruke lys grå bakgrunn av to grunner:
- Den er lett og tar ikke for mye fokus i seg selv (lar innholdet få fokus)
- Det er den mest brukte bakgrunnsfargen på lignende elementer ellers i tjenesten (mest konsistent). Se f.eks. http://www.telemark.no/Politikk

**Comment by evasdrugg** [comment]
Er fargen knæsj grønn? Jeg trodde den var mer blå. Men den stripa, det var et ønske å gjøre det som http://www.rogfk.no/ - en stripe mellom bilde og tekstfelt? Forståelig? :) 

Men hvis det er grå som er best - så bør den i hvertfall være gjennomgående på det jeg nevnte over. Noe å tilføye her, @zrrrzzt?

**Comment by KnutSv** [comment]
Ah.. jeg så på den over, ganske like hex-koder, men veldig knæsj ja. Tingen er at så kraftige farger må brukes forholdsvis sparsomt og helst i små størrelser, som på knapper etc. for at de ikke skal «ta over» designet.

På tab-bar og knapper brukes det en dus versjon av grønnfargen i profilen. Dette er vel så vidt jeg husker i henhold til designet fra Metro. Jeg syns det er en fornuftig bruk av farger for å skille to forskjellige funksjoner: bakgrunn og handling. Hvis tab-bar-elementer og knapper blir grå blir det mindre tydelig at de kan trykkes på. Samtidig vanner vi ut dette visuelle virkemiddelet ved å bruke den duse grønnfargen på større bakgrunnsflater.

**Comment by KnutSv** [comment]
Jeg skjønner fortsatt ikke hvor du tenker den stripa plassert. Rogaland har en helt annerledes slider med tekst til høyre for bildet.

**Comment by zrrrzzt** [comment]
Klarer du å ta en skjermdump med beskrivelser på @evasdrugg 

Bare gi et kjapt estimat på tidsbruk @KnutSv ... når vi har komme frem til felles forståelse av oppgaven

**Comment by evasdrugg** [comment]
![skjermbilde kopi](https://cloud.githubusercontent.com/assets/12184881/8251466/0922238c-167d-11e5-86cd-999a5354c6df.png)

**Comment by KnutSv** [comment]
Jeg forstod at det var den hvite vertikale skillelinjen mellom bildet til venstre og tekstboksen til høyre som du mente. Det jeg skrev var at det er en helt annen type slider med bilde til venstre og tekst til høyre. Telemark har en slider med tre kolonner hvor hvert element har bilde over og tekst under.

**Comment by evasdrugg** [comment]
Ja, vi ønsker en helt annen type slider - ikke med tre, men som Akershus og Rogaland med en - jeg forsøkte å forklare i det øverste innlegget... Ser nå at det var dårlig forklart!

**Comment by Maiskolba** [comment]
Jeg har endret slideren til å vise 1 istedenfor 3, og lagt inn den grønne bakgrunnsfargen - http://devtelemark.vangenplotz.net/
Alt annet av styling må Knut ta seg av.

**Comment by zrrrzzt** [comment]
Det ser ganske så bra ut :-)

Men, er det mulig å fjerne litt av luften mellom sliden og navigasjonskontrollen under? Eller tramper vi da i beddet til @KnutSv ?

**Comment by Maiskolba** [comment]
Dette er ting @KnutSv må ta seg av, design og meg går ikke overens ;-)

**Comment by zrrrzzt** [comment]
Har samme forhold til design selv. Rull likevel ut endringen. Den er fortsatt bedre enn hva som er ute pr i dag.

**Comment by Maiskolba** [comment]
Den er grei, nå er det rullet ut.

**Comment by evasdrugg** [comment]
Åj - nå ser jeg nytt kampanjefelt - så moro - men skriftstørrelsen er veldig liten, både på tittel og tekst - hadde vært fint om dette kunne blitt en del større. Har ferie og er egentlig ikke online. @zrrrzzt

**Comment by zrrrzzt** [comment]
Setter opp skriftstrls som egen issue etterhvert om ikke du tar det.
