### ISSUE TITLE
Legg word-wrap: normal i css

### ISSUE THREAD

**Issue by zrrrzzt** [telemark/telemarkBundle#136]
Dette løser alle problemer med fønky orddeling.

Har "løst" dette mange ganger her tidligere, men ser at det mangler i selve rammeverket. Lagt inn issue der også.

**Comment by zrrrzzt** [comment]
løses best [her](https://github.com/telemark/websider-malverk/issues/31) og så rulles ut

**Comment by zrrrzzt** [comment]
![screen shot 2015-06-25 at 14 35 41](https://cloud.githubusercontent.com/assets/2197936/8354329/954c3ffe-1b47-11e5-98c7-ac0615a5c48f.png)

**Comment by zrrrzzt** [comment]
Har lagt inn midlertidig fix på nettsiden. 
Lagt forslag til løsning her https://github.com/telemark/websider-malverk/issues/31#issuecomment-115361764

**Comment by evasdrugg** [comment]
Kan vi ta opp denne igjen? @zrrrzzt  Jeg får stadig tilbakemeldinger fra folk om rare orddelinger! Også utenfra organisasjonen. Her er mail fra opplæringsavdelingen: 

"Det gjelder ikke bare hvordan ting vises her hos oss, men brukere av våre hjemmesider melder om samme feil når de er på vår hjemmeside…… (orddelingsproblematikken ser ikke ut til å være der ved bruk av mobil; bare PC)."

**Comment by KnutSv** [comment]
Slik, det lå igjen noe grums der som jeg har fjerna nå. Koden var overstyrt et annet sted, men det er mulig at noen vendor-prefixede verdier ikke ble overstyrt og derfor påvirka gamle nettlesere. Når skal det funke for alle hvertfall.

**Comment by evasdrugg** [comment]
Hurra!
