### ISSUE TITLE
Ny side åpnes når PDF lastes ned

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#137]
Når man skal laste ned PDF, kommer det opp en ny side. Vi vil at PDF skal lastes ned automatisk. Mener at jeg meldte inn dette tidligere, @zrrrzzt, men kan hende jeg bare drømte det.

http://www.telemark.no/Media/Files/Aktuelt/Bypakke-Grenland-brosjyre-juni-2015

**Comment by Paalmessenlien** [comment]
Den er meldt inn for fil nedlasting generelt. Dette er en funksjon som ikke følger med nye ez som standard så vi må utvikle den. Rekker nok desverre ikke å se på det før ferien. Men tar det opp igjen når jeg er tilbake. God sommer

**Comment by zrrrzzt** [comment]
Duplikat av #115
