### ISSUE TITLE
Feilmelding i eZ

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#138]
Prøver å bytte navn på infoboks, får feilmelding:

http://www.telemark.no/siteadmin/Vaare-tjenester/Arealbruk-og-transport/Kollektivtransport/Planer 

"Utkastet ble bare delvis lagret.
Tekst:
Node 12853 finnes ikke."

**Comment by zrrrzzt** [comment]
Dette er en driftsfeil og ikke utseende/funksjonsfeil. Ta kontakt med V&P

**Comment by evasdrugg** [comment]
Ok
