### ISSUE TITLE
sitemap.xml

### ISSUE THREAD

**Issue by zrrrzzt** [telemark/telemarkBundle#141]
Det kan virke som om denne ikke oppdateres. Ligger en del sider i den som gir 404. Et eksempel er denne http://www.telemark.no/Vaare-tjenester/Folkehelse/Skoler/Tobakk-Rus
- Sjekk at den genereres daglig
- Sjekk at den kun inneholder forsiden, mapper og artikler

**Comment by vangpl** [comment]
Den kjørte ikke riktig lengre. Jobben ble ikke plukket opp av ez sin cronjob. Så jeg har lagt den inn som en egen jobb som kjører hver kveld kl 22:00. 
Manuell generering kan også startes her: http://www.telemark.no/siteadmin/googlesitemapdynamic/sitemap/2

La til frontpage klassen til visning. Dette tar også med under sider som bruker denne.
