### ISSUE TITLE
Kampanjeboksen ser ikke bra ut på undersider

### ISSUE THREAD

**Issue by zrrrzzt** [telemark/telemarkBundle#144]
Eksempel: http://www.telemark.no/Vaare-tjenester/Kulturminner

Kan se ut til at kampanjebokser i den størrelsen bør brytes om til bildet øverst og tittel/tekst under

**Comment by KnutSv** [comment]
Vet du hvilke templates, bortsett fra forsiden, hvor det brukes slider på denne måten?

**Comment by zrrrzzt** [comment]
Mappe er vel være eneste naturlige sted å benytte seg av slider... evt også artikkel

Det ligger en template embed-inline/slide_container.html.twig som jeg tror brukes ved embed i mapper/artikler.

**Comment by KnutSv** [comment]
Ok, skal kikke på det

**Comment by KnutSv** [comment]
Som jeg mistenkte er ikke "embed-inline/slide_container.html.twig" i bruk. Begge steder betnyttes: "line/slide_container.html.twig". Jeg vet ikke hvor den kalles fra, evt. hvordan jeg kan endre den. Assigner til @Paalmessenlien , kanskje han kan ordne det slik at vi får to ulike templates.

**Comment by Paalmessenlien** [comment]
Laster opp på prod nå. Ble mye fiks faks det her for å få til.
Templates for visning av slider embed på side gjøres her:
embed-inline/sllide-container.twig
embed-inlline/slide.html
responsive/image.html.twig (endring under slider valg)

Regner med at det er siste filen endringene blir.

**Comment by KnutSv** [comment]
@Paalmessenlien Regner med du har sjekket inn selv om du ikke har referert issue i commit. Som nevnt tidligere får jeg ikke sett på dette før tidligst om 3 uker når jeg er tilbake fra ferie.

**Comment by zrrrzzt** [comment]
Skal vel kanskje ikke stå Embed i boksen heller ;-)

http://www.telemark.no/Vaare-tjenester/Kulturminner

![screen shot 2015-07-31 at 15 10 56](https://cloud.githubusercontent.com/assets/2197936/9007959/96bee2e0-3796-11e5-8ac3-e78e1579fbc8.png)

**Comment by Paalmessenlien** [comment]
Det kunne nok stått styggere saker der etter runda med overrides krangel
idag:)

2015-07-31 15:12 GMT+02:00 Geir Gåsodden notifications@github.com:
