### ISSUE TITLE
Sidemeny validerer ikke

### ISSUE THREAD

**Issue by zrrrzzt** [telemark/telemarkBundle#146]
http://validator.w3.org/nu/?useragent=Validator.nu/LV%20http://validator.w3.org/services&doc=http://www.telemark.no/Vaare-tjenester/Folkehelse/Aktuelt/Tar-fagene-ut 

```
Error: Element ul not allowed as child of element ul in this context. (Suppressing further errors from this subtree.)
From line 319, column 5; to line 319, column 20
enu">↩    <ul class="nav">↩
```

**Comment by Paalmessenlien** [comment]
Done!.. KPN MENU#"#"¤#"¤"#¤#"¤"#SD#R%#"%#
