### ISSUE TITLE
custom validerer ikke

### ISSUE THREAD

**Issue by zrrrzzt** [telemark/telemarkBundle#150]
Vet ikke helt hvilket element som er skyld i dette: https://validator.w3.org/nu/?useragent=Validator.nu/LV%20http://validator.w3.org/services&doc=http://www.telemark.no/Aktuelt/2014/Ny-hoeringsrunde-paa-handelsbestemmelsene-for-Grenland

**Comment by Paalmessenlien** [comment]
Det kan se ut som det ligger en custom quote blokk lagt inn i teksten på høyreboksen. Denne har ingen styling og er vel ikke i bruk lengre? Kan se ut som den feiler fordi den ligger i høye boksen også.

**Comment by zrrrzzt** [comment]
Vet ikke om den er i bruk noen andre steder, men den var vel stylet grå/blått tidligere.
Er uansett koden som feiler og ikke stylingen, så om det er mulig å fikse den hadde det vært topp :-)
Blockquote er i alle fall definert i cssen.

**Comment by Paalmessenlien** [comment]
Lagt inn custom tag i symfony kode. Og endret så den validerer. Men nå må quote klassen styles om. Alt for stor tekst. Gir ballen videre til Knut for å fikse dette.

**Comment by KnutSv** [comment]
FYI: Jeg går ut i ferie om 2 timer og får ikke sett på dette før om tidligst 3 uker

**Comment by KnutSv** [comment]
Er dette fikset? Jeg finner ikke noe custom element referet i lenken.

**Comment by zrrrzzt** [comment]
Custom er fikset, designet not so much http://www.telemark.no/Aktuelt/2014/Ny-hoeringsrunde-paa-handelsbestemmelsene-for-Grenland

Ganske stor tekst ser du i infoboksen
