### ISSUE TITLE
Kampanjeslider: Tekst vises ulikt i msie og chrome

### ISSUE THREAD

**Issue by zrrrzzt** [telemark/telemarkBundle#151]
http://www.telemark.no/ i sliden vedr skoleskyss brytes mye av teksten rart i msie

**Comment by Tmholen** [comment]
Her er kampanjesliden i Chrome. Det er slik den skal være:
![skjermbilde_chrome](https://cloud.githubusercontent.com/assets/8641408/9061287/19519942-3abb-11e5-9fda-b3ab02931027.JPG)

I msie så kutter den teksten midt i ordet.
![skjermbilde_explorer](https://cloud.githubusercontent.com/assets/8641408/9061303/3da4b644-3abb-11e5-98af-b2486ed690b7.JPG)

**Comment by Tmholen** [comment]
Her er kampanjesliden i Chrome. Slik skal den være:
![skjermbilde_chrome](https://cloud.githubusercontent.com/assets/8641408/9061353/6a06079c-3abb-11e5-8ceb-c2ff863ef1d9.JPG)

Her er den i msie.Den er feil, den kutter ordene midt i setningen:
![skjermbilde_explorer](https://cloud.githubusercontent.com/assets/8641408/9061367/802d48b4-3abb-11e5-81e3-85d1b1ac088f.JPG)

**Comment by zrrrzzt** [comment]
Ahh, takk for bildene @Tmholen Det er denne gamle rakkeren her https://github.com/telemark/telemarkBundle/issues/136 som er i farta igjen @Paalmessenlien

**Comment by Paalmessenlien** [comment]
Fikset. Må få knut til å legge denne inn i malverket.

**Comment by zrrrzzt** [comment]
Åpner du issue i repoet?
