### ISSUE TITLE
Størrelse på bildetekst

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#152]
Hei, bildeteksten i artikler har plutselig blitt veldig stor. Har det sammenheng med kampanjen? 

Det ser i hvert fall ikke så pent ut: http://www.telemark.no/Vaare-tjenester/Folkehelse/Aktuelt/Naa-blir-det-liv-og-roere-i-Krageroe @zrrrzzt @Paalmessenlien

**Comment by zrrrzzt** [comment]
Mulig sammenheng med denne? https://github.com/telemark/telemarkBundle/issues/142

**Comment by evasdrugg** [comment]
Fremdeles veldig stor bildetekst, som ikke ser no' pent ut. Noen som får se på denne snart?

**Comment by zrrrzzt** [comment]
Setter du noen på saken @Paalmessenlien ?

**Comment by KnutSv** [comment]
Riktig at det sammenheng med #142 , ser på det i løpet av de neste dagene.
