### ISSUE TITLE
id attribute not uniqe

### ISSUE THREAD

**Issue by zrrrzzt** [telemark/telemarkBundle#153]
På enkelte sider får vi wcag feil på id attribute not unique som for eksempel her: http://achecker.ca/checkacc.php?id=32bab43d166df41d242aec90e6ec6c04d9eb241c&uri=http://www.telemark.no/Aktuelt/2014/Dette-betyr-revidert-nasjonalbudsjett-for-Telemark 
Det kan se ut til at synderen er `eztoc_1_1` https://validator.w3.org/nu/?useragent=Validator.nu/LV%20http://validator.w3.org/services&doc=http://www.telemark.no/Aktuelt/2014/Dette-betyr-revidert-nasjonalbudsjett-for-Telemark

**Comment by Paalmessenlien** [comment]
eztoc er noe eZ legger på headere. Det har tidligere vært brukt for anker linker og utlisting av innholdslister o.l. Utfordringen her er at det brukes header i høyre blokken også. Denne vet ikke at det finnes eztoc også i hoved teksten. Derfor blir det to like id'r.
