### ISSUE TITLE
For mange personprofiler?

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#155]
Hei @zrrrzzt 

Fra Anne Cecilie: 

Jeg skal legge inn flere kontakter her på areal og transport, blant annet gjengen på gråtenmoen. Se nå når jeg har lagt til ann –carin helt nederst. Det er vel ikke ubegrenset plass på denne siden, men hva gjør jeg da?

http://www.telemark.no/Vaare-tjenester/Arealbruk-og-transport/Kontakt-oss

**Comment by zrrrzzt** [comment]
Siden skal utvide seg etter behov, så her må noen fikse litt :-)

**Comment by evasdrugg** [comment]
Flotters

**Comment by Maiskolba** [comment]
Jeg er litt usikker på hva funksjonen "kompaktvisning" på personprofiler betyr, for meg ser det ut som de vises helt likt. Uansett, jeg huket av for dette på Ann-Carin og da la hun seg fint på egen linje under. Tror dette er noe Knut må se på når han kommer tilbake, tror det har noe med cssen å gjøre.

**Comment by zrrrzzt** [comment]
@Maiskolba Takker! Da lever vi med det enn så lenge @evasdrugg ?

**Comment by zrrrzzt** [comment]
Lukker denne.

Tror problemet egentlig skyldes at det ble blandet kompakte og ikke kompakte profiler. Det skal man helst ikke gjøre.
