### ISSUE TITLE
Facebookarrangement

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#157]
Hei, kan du legge inn Facebookarrangement i infoboks på denne siden, @zrrrzzt?

http://www.telemark.no/Politikk/Valg-2015

Lenke til Facebook-arrangementet Valg i Telemark:

https://www.facebook.com/events/1659862004229294/

**Comment by zrrrzzt** [comment]
Facebooks social plugins støtter kun pages og ikke events https://developers.facebook.com/docs/plugins
