### ISSUE TITLE
Ikke vise flik når det kun er en av de

### ISSUE THREAD

**Issue by zrrrzzt** [telemark/telemarkBundle#158]
Vi bruker flikbokser (tabboks/tabboks_tab) enkelte steder kun som innholds element. I tilfellene vil vi gjerne at fliken ikke skal vises.

Eksempel: http://www.telemark.no/ på forsiden står det en liten gul knapp "Aktuelt", denne vil vi gjerne ha bort.

Altså: ikke vise flik på flikbokser med kun en flik (se det raskt 10 ganger etter hverandre du)

**Comment by Maiskolba** [comment]
Ønsker dere da at det skal stå "vanlig" overskrift der istedet eller ingenting i det hele tatt?

**Comment by zrrrzzt** [comment]
ikke noe, ta vekk hele fliken
