### ISSUE TITLE
Piler på kampanje

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#159]
Det sier seg ikke selv at man kan klikke for å se flere kampanjer på forsiden, «Neste» er vanskelig å se for folk. Vi ønsker oss store hvite piler, lit ala http://www.akershus.no/, men kanskje større. Ka du tru, @zrrrzzt?

**Comment by zrrrzzt** [comment]
Jeg synes ikke et par hvite piler tilfører noe særlig brukervennlighet. Tror også at denne formen for kampanjeslider er såpass vanlig at de som ønsker å se mer, klarer nettop det.

Men, for all del. Er villig til å ta feil jeg.

**Comment by evasdrugg** [comment]
Det var en tekstdoktor som nevnte det også neste uke. Hun forstod ikke at det gikk an å klikke videre.
