### ISSUE TITLE
Kampanjefelt på områdeforsider ser ikke bra ut

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#161]
Se kampanjefeltet for Kulturminner. Hva skjer her? 

http://www.telemark.no/Vaare-tjenester/Kulturminner

**Comment by KnutSv** [comment]
Problemet er at det brukes samme template som for slideren på forsiden. Det funka fint når teksten var under, men med teksten og pilene på siden bryter den.

Vi trenger en klasse på "div.slider" slik at vi kan style slideren slik som på mobil.

**Comment by evasdrugg** [comment]
Aha...

@zrrrzzt, Lise på kulturminne sier de kun trenger kampanjehjul på forsiden deres, ikke på arkeolog og på nyere tid - men dette kan de (vi) fjerne enkelt selv?

**Comment by zrrrzzt** [comment]
@evasdrugg ja, det ligger vel bare som et objekt under mappen og bør kunne slettes uten problemer.
De kan evt skjule det først for å se hvordan det vil se ut.

@KnutSv har du tid til å se på dette i dag? Tror svært mange av områdesidene våre bruke kampanjeslideren.

**Comment by evasdrugg** [comment]
@zrrrzzt @KnutSv Avvent - jeg tror det først og fremst er Kulturminnevern som bruker kampanjefelt/slider. De fleste bruker flikboks på sine forsider.

**Comment by zrrrzzt** [comment]
Jeg mener det bør være mulig for alle å bruke slideren, hvor som helst. Derfor ikke noe problem om @KnutSv fikser slideren så den tilpasser seg området den ligger på etter skjermstørrelse/plass.
