### ISSUE TITLE
Prioritering funker ikke

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#164]
Prøver å prioritere her, men får det ikke til? 

http://www.telemark.no/siteadmin/Fylkeskommunen/Fotavtrykk-Telemark/Priser-og-stipender

**Comment by zrrrzzt** [comment]
Ser ut til at du har gjort alt du skal siden de sorteres korrekt i admin.
Da får noen andre lete etter feil

**Comment by evasdrugg** [comment]
Ok

**Comment by Maiskolba** [comment]
Når en artikkel har flere plasseringer vil den ta prioriteringsverdien som ligger på hovedplasseringen.

**Comment by zrrrzzt** [comment]
Tror eksempelet det vises til her har artiklene ligger samme sted som prioritering er satt, men det kan evt @evasdrugg bekrefte/avkrefte

**Comment by evasdrugg** [comment]
Ahaaaaa! Det er _noen_ som ikke ligger der (jeg har mast på det). Men da vet jeg hva grunnen er. Takk.

**Comment by zrrrzzt** [comment]
kløsed
