### ISSUE TITLE
Søke på tlf. nr i ansattbase

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#168]
Hvorfor kan man kun søke på tlf.nr. i ansattbase? Finnes det en mulighet for å få dette til?

http://apps.t-fk.no/ansatte/

**Comment by zrrrzzt** [comment]
Lukker denne fordi ansattbasen er eget produkt som ikke hører til websiden. Når vi oppdatere alle "på-siden-løsningene" våre vil de få mye bedre søk.

**Comment by evasdrugg** [comment]
Ok, tenkte ikke på det ☺

Fra: Geir Gåsodden [mailto:notifications@github.com]
Sendt: 9. oktober 2015 14:46
Til: telemark/telemarkBundle telemarkBundle@noreply.github.com
Kopi: Eva Susanne Drugg eva.susanne.drugg@t-fk.no
Emne: Re: [telemarkBundle] Søke på tlf. nr i ansattbase (#168)

Lukker denne fordi ansattbasen er eget produkt som ikke hører til websiden. Når vi oppdatere alle "på-siden-løsningene" våre vil de få mye bedre søk.
