### ISSUE TITLE
Feil alternativ bildetekst på kampanjeslider 

### ISSUE THREAD

**Issue by zrrrzzt** [telemark/telemarkBundle#170]
Den alternative bildeteksten på kampanjesliden hentes fra selve bildeobjektet og ikke fra slide-objektet.

Når bilder brukes som link skal den alternative bildeteksten beskrive hva som skjer når man trykker på linken og ikke beskrive bildet. Så feltet alt_image_text fra klassen slide er de som skal vises på disse.

På http://www.telemark.no/ skal den alternative bildeteksten på buss-sliden mao være: "Klikk på bildet for å lese mer om tjenestekonsesjonskontrakt for ekspressbuss" og ikke være tom som den er nå

**Comment by Maiskolba** [comment]
Den alternative bildeteksten er ikke tom på noen av bildene i kampanjeslideren, men tenker du på title på a-taggen? Den gule boksen som noen ganger kommer opp når man holder musa over en link?

**Comment by zrrrzzt** [comment]
Tenker på alt-property i img-taggen. Den er ikke tom, men den viser fra bilde-objektet og ikke slide-objektet. Når bildet brukes som link må en annen tekst inn.

**Comment by Maiskolba** [comment]
Skjønner, nå er dette endret.
