### ISSUE TITLE
Orddelingsfeil

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#172]
Hei, @zrrrzzt . Igjen får vi meldinger om orddelingsfeil på nett. Kollegaen bruker Explorer. Under "Datafiler for nedlasting".

![orddeling](https://cloud.githubusercontent.com/assets/12184881/10784434/5e14343c-7d5e-11e5-9280-66b21c89dc44.jpg)

http://www.telemark.no/Fylkeskommunen/OEkonomi/Budsjetter/Budsjett-2016-2019

**Comment by zrrrzzt** [comment]
Denne er til dere @Paalmessenlien 
Plz lag evig fiks denne gangen :-)

**Comment by Paalmessenlien** [comment]
Klarer ikke å gjenskape dette problemet i IE hos meg.Koden ser også riktig ut fra det jeg kan se. Det ligger ikke igjen noe cache hos brukeren her?

**Comment by evasdrugg** [comment]
Vet ikke. Men vi får jo innimellom disse meldingene fra kolleger - og fra kolleger som har brukere som opplever det samme.

**Comment by evasdrugg** [comment]
Svar fra kollega: "Jeg får rar ordeling i Explorer men ikke i Google Crome."

**Comment by Paalmessenlien** [comment]
Klarer du å finne ut hvem IE versjon dette gjelder?

2015-11-03 14:16 GMT+01:00 evasdrugg notifications@github.com:

**Comment by zrrrzzt** [comment]
Sjekket IE via citrix og kikket på css.
Ikke noe problem i IE (på siden som ble brukt som eksempel i alle fall)
css ser ut til å inneholde word-wrap: normal slik den skal

**Comment by Paalmessenlien** [comment]
Da må det ligge igjen noe i browseren til brukeren som gjør dette. Be henne
prøve å slette browser cache.. CTRL, SHIFT + DELETE.

2015-11-04 12:12 GMT+01:00 Geir Gåsodden notifications@github.com:
