### ISSUE TITLE
URL og lenking for kalender

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#173]
På http://www.telemark.no/Vaare-tjenester er det linkblokk for kalender - den ønsker jeg skal gå direkte til http://www.telemark.no/Vaare-tjenester/Kalender 

Men får ikke til..

http://www.telemark.no/siteadmin/Vaare-tjenester/Kalender3

I tillegg ønsker jeg at kalenderfunksjonen også kommer på nedtrekksmeny for Våre tjenester.

**Comment by zrrrzzt** [comment]
Du hadde pekt til feil intern ressurs.

Når du bruker interne ressurser så overstyrer du også innholdet i den manuelle du hadde fylt ut tidligere på linkblokken.

Ang ønsket om å få den inn i menye... vennligst legg det inn som egen issue. Så skal jeg sette den til ønske osv

**Comment by evasdrugg** [comment]
Takk!
