### ISSUE TITLE
Søknadsskjemaer på nett

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#176]
Fagredaktører har behov for søknadsskjemaer på nett ASAP. Hva gjør vi? 

Søknader for prosjekter,arrangement og tiltak innen regional utvikling, fem priser totalt. 

Dette haster, @zrrrzzt...

**Comment by zrrrzzt** [comment]
Dette må nok gå via andre, byråkratiske kanaler.

**Comment by evasdrugg** [comment]
Fin label, haha. Jeg sendte e-post til Tania i går, ikke fått svar ennå.
