### ISSUE TITLE
Google-søk

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#177]
Søker på "Fylkesmannnen i Telemark" i Google, og får opp dette: 

![skjermbilde](https://cloud.githubusercontent.com/assets/12184881/11365896/024a54b8-92aa-11e5-8b7d-cb9e9e7497c1.PNG)

Kommer inn på www.telemark.no.... Hvordan har dette skjedd?

**Comment by zrrrzzt** [comment]
Google gjør som de vil og Fylkesmannen i Telemark er unclaimed business. 
Dermed lager google en oppføring som inneholder det de tror stemmer.
Vi kan ikke gjøre noe med det... utover å kanskje tipse kommunikasjonsavdelingen hos Fylkesmannen om at de bør gjøre som oss: Ta kontroll over egen Google-oppføring
