### ISSUE TITLE
Antall artikler som vises under Aktuelt

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#178]
Hei, det går bare til 10 sider på Aktuelt: http://www.telemark.no/Aktuelt?page=10 

Hva skjer med artiklene som er skrevet før 26. mai 2015? Vil gjerne vise de også? For alle år egentlig? Vil at det skal være mulig å gå så langt tilbake som mulig.

**Comment by vpbjorn** [comment]
Dette er allerede løst #188
