### ISSUE TITLE
Kontakt oss

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#179]
Visningen på kontakt oss under Nyskaping viser tre og tre i rekke? 

Har det noe med kompakt visning å gjøre?

http://www.telemark.no/Vaare-tjenester/Naeringsutvikling/Kontakt-oss2

**Comment by zrrrzzt** [comment]
Sjekk hva det er krysset av for :-)

**Comment by evasdrugg** [comment]
Skal alle være krysset av for "kompakt visning" for at det er to i bredden?

**Comment by zrrrzzt** [comment]
Skal jeg tippe, litt kvalifisert, vil jeg tro at kryss for kompakt visning gir 3 i bredden og ikke kryss gir 2.
Det var i alle fall oppsettet på den opprinnelige siden.

**Comment by evasdrugg** [comment]
Årna seg. Måtte krysse av for kompakt visning for å vise to i bredden.
