### ISSUE TITLE
Rar visning Aktuelt på Folkehelse

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#180]
http://www.telemark.no/Vaare-tjenester/Folkehelse/Aktuelt

Vi la inn sånn at man kan bla under Aktuelt på Folkehelse. Da forandret visningen seg, og gamle artikler legger seg tidlig. Og kun tre. Det burde jo vært 6? Valgte "Vis paginering" og 6 elementer.

**Comment by zrrrzzt** [comment]
Viser 3 på forsiden og 6 på de neste såvidt jeg kan se.

Hva sorteringen angår er jeg usikker. Alt ser ganske hulter til bulter ut.

**Comment by evasdrugg** [comment]
Men burde jo uanz vist 6 på første side? Fint om @Paalmessenlien tryller :)

**Comment by zrrrzzt** [comment]
er nok @Maiskolba som er magikeren her

**Comment by vpbjorn** [comment]
Da er dette ordnet Paginering og 6 stykker per side.

Dette skyldes at utlistingen av underelementer var basert på søk i content og ikke location - dermed var det mainLocation som ble forsøkt vist. Denne kunne være skjult.

d6df093161d8e7408792509362d30465fc42e301
