### ISSUE TITLE
Tredje rad i artikkel

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#181]
Fra fagredaktører Anne Cecilie: 

Er det mulig å få lagt inn en tredje rad her, slik at man får utnyttet siden bedre?
Skal jo legge inn alle som frem til nå har jobbet på Tuftebygget….

http://www.telemark.no/Vaare-tjenester/Arealbruk-og-transport/Kontakt-oss

**Comment by evasdrugg** [comment]
Det er et eneste virrvarr når AC har lagt inn alle som skal inn: http://www.telemark.no/Vaare-tjenester/Arealbruk-og-transport/Kontakt-oss

**Comment by zrrrzzt** [comment]
Det er også et virrvarr på hvorvidt kompakt visning er av og på. Man må bruke enten det ene eller det andre på alle som er listet på samme side

**Comment by zrrrzzt** [comment]
tror det korrekte er at alle skal ha kompakt dersom det skal være 3 i bredden
om det ikke stemmer er det feil slik at vi melder feil til V&P

**Comment by evasdrugg** [comment]
Okei
