### ISSUE TITLE
Kampanje på forside

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#182]
Hvorfor vises denne på forsiden når den er skjult i eZ?

http://www.telemark.no/siteadmin/Forsidekampanje/Privatisteksamen

**Comment by zrrrzzt** [comment]
Antar det er denne du ser: http://www.telemark.no/siteadmin/Forsidekampanje/Privatisteksamen2 den er ikke skjult

**Comment by evasdrugg** [comment]
Kult
