### ISSUE TITLE
Direkte lenke ledige stillinger

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#183]
Hei, kan du fikse slik at "Ledige stillinger" helt øverst på siden går direkte til https://hrm.btvregion.no/tfk_recruitment/opening;jsessionid=6AD3FEAEEDCDB00282E4E58CF4E19BDF?0

Bitte sehr.

**Comment by zrrrzzt** [comment]
Er det avklart med personal?

**Comment by evasdrugg** [comment]
Jepp. Ragnhild.

**Comment by zrrrzzt** [comment]
Snabelbra :+1: Fikser i morgo

**Comment by zrrrzzt** [comment]
antar dette da også gjelder linken til Ledige stillinger i footeren @evasdrugg ?

**Comment by evasdrugg** [comment]
Ya

**Comment by zrrrzzt** [comment]
fixed
