### ISSUE TITLE
Prioritering funker ikke

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#184]
Har sortert etter prioritet og rekkefølge, og lagt inn nummer for prioritering. Ser ok ut i siteadmin, men fungerer ikke på verdensveven?

http://www.telemark.no/Planer/Regionale-planer

http://www.telemark.no/siteadmin/Planer/Regionale-planer

**Comment by vpbjorn** [comment]
Da er dette løst for alle steder som har bruke Item:children. Denne er erstattet med Item:childrenItems og ny child_items_loop.html.twig. 
e55c243f52568f0a45f76e87a918c58b21cbed1a
