### ISSUE TITLE
Møtekalender

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#185]
Hei, da ser det ut som politiske møter er oppdatert på opengov.

http://opengov.cloudapp.net/Meetings/tfk 

Jeg er usikker på om vi skal ha med Arbeidsutvalget for Hovedutvalet for kompetanse, Klagenemnda for skolesaker, Telemark fylkeskommunale klagenemnd og Telemark interkommunale næringsfond. Det har vi ikke hatt tidligere. Kan høre med Stig.

Får du tryllet og hentet dette inn på et vis på www.telemark.no/politikk?

**Comment by zrrrzzt** [comment]
Ikke med det første. Hadde ikke primært tenkt å lage løsningen for eZ.
Er vel Stigs ansvar enn så lenge å få dette på lufta med evt klipp og lim?

**Comment by evasdrugg** [comment]
Det er ikke jeg som kan bestemme at det er Stig som skal gjøre det. Vi (jeg) har "alltid" gjort det. Før høre med sjefa hva jeg gjør videre.
