### ISSUE TITLE
Skjult infoboks vises

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#186]
Hei, prøver å skjule infoboks, men den vises. Derfor jeg prøvde cashetømming.

http://www.telemark.no/siteadmin/Fylkeskommunen/Fotavtrykk-Telemark  

Denne infoboksen:

http://www.telemark.no/siteadmin/Fylkeskommunen/Fotavtrykk-Telemark/Tidligere-prisvinnere

**Comment by vpbjorn** [comment]
Løst etter å ha fikset #184
