### ISSUE TITLE
Artikkelvisning - viser ikke alle artikler

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#188]
http://www.telemark.no/Aktuelt

Det er lagt inn antall per side visning her. Opp til ti sider. Siste artikkel som vises er fra august 2015.
Eldre artikler som vi har publisert er vanskelig å finne. Derfor må dette på plass asap.

**Comment by vpbjorn** [comment]
Endret sortering for arkivet i controlleren 
https://github.com/telemark/telemarkBundle/commit/46cc96012dae8a11472ca850c7bc013b535d0b11
