### ISSUE TITLE
Feil i kalender

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#192]
Fra Lene Sjølie: 

Når jeg står i en kalenderhendelse i vår folkehelsekalender – eksempelvis her: http://www.telemark.no/Vaare-tjenester/Folkehelse/Hva-skjer2/Skolemaaltidet-31.-mars-2016-09-30-00
..og trykker på pilen for neste måned i kalenderen:

… kommer jeg bare til forsida på www.telemark.no – ikke til neste måned ;)

Hvis jeg står på hovedsida for kalenderen: http://www.telemark.no/Vaare-tjenester/Folkehelse/Hva-skjer2 og trykker på pila mot neste måned blar den videre slik den skal 

Noe du eller dine venner i V&P kan fikse? 

**Comment by vpbjorn** [comment]
Da skal dette fungere som det bør.
