### ISSUE TITLE
Kortlenke fungerer ikke

### ISSUE THREAD

**Issue by evasdrugg** [telemark/telemarkBundle#193]
Hei, opprettet kortlenke for denne artikkelen:

http://www.telemark.no/Vaare-tjenester/Utdanning/Aktuelt/Sommerskole-2016 

til www.telemark.no/sommerskole

Får feilmelding: 

"Oops! An Error Occurred

The server returned a "404 Not Found".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused."

En annen artikkel hadde samme kortlenke, men den er fjernet.

**Comment by zrrrzzt** [comment]
kan du forsøke å fjerne den du laget sist også.. og så legge den inn påny (når du er sikker på at lenken er ledig)

**Comment by zrrrzzt** [comment]
Det er denne lenken som ikke funker http://www.telemark.no/Vaare-tjenester/Utdanning/Aktuelt/Sommerskole-2016 sommerskoleforkortelsen peker videre, så den fungerer aldeles utmerket ;-)

**Comment by zrrrzzt** [comment]
artikkelen det pekes til står satt til skjult

**Comment by evasdrugg** [comment]
Haha. Beklager for at du brukte tid på dette, @zrrrzzt. Dårlig dag i går.
