### ISSUE TITLE
target="_SELF" i venstremeny

### ISSUE THREAD

**Issue by zrrrzzt** [telemark/telemarkBundle#85]
i venstremeny på interne linker står target="_SELF" og ikke target="_self". Det gjør at i alle fall Chrome på Mac åpner alle linker i menyen i ny tab

Eksempel: http://symftelemark.vangenplotz.net/Vaare-tjenester/Arealbruk-og-transport

Den gjør også uppercase på linker som er target="_blank" se http://symftelemark.vangenplotz.net/Fylkeskommunen for eksempel

Har sjekket parts:menu_left.html.twig og den ser korrekt ut

**Comment by zrrrzzt** [comment]
Problemer også på Vivaldi for Mac og Safari. Ikke problem i FireFox for Mac

**Comment by Paalmessenlien** [comment]
menu_left er nok ikke i bruk noen steder så den kan vi nok slette.
