### ISSUE TITLE
og-metadata på artikler

### ISSUE THREAD

**Issue by zrrrzzt** [telemark/telemarkBundle#94]
På alle artikler ønsker vi disse metadataene inn

```
<meta property="og:title" content="<artikkelens tittel>">
<meta property="og:site_name" content="Telemark fylkeskommune">
<meta property="og:url" content="<artikkelens url>">
<meta property="og:description" content="<artikkelens meta description, evt intro eller short_into>">
<meta property="og:type" content="article">
<meta property="og:locale" content="no_NO">
<meta property="og:image" content="<url til responsive_12 utgaven av bildet>">
```

**Comment by Paalmessenlien** [comment]
Tregner mata data tagger for facebook på artikler. 
Responsive bilder gjør at de ikke vises på FB når man deler link lengerderfor vil jeg ha inn opengraph metadata. Eks på link med metadata: http://www.telemark.no/Aktuelt/Fylkesordfoerer-skuffet-over-stortingsmelding

**Comment by zrrrzzt** [comment]
Godt redskap for å sjekke: https://developers.facebook.com/tools/debug/

**Comment by zrrrzzt** [comment]
fixed
